In [2]:
# Import the dependencies
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf

# Read the input data
hr_df = pd.read_csv('./Data/HR-Employee-Attrition.csv')
hr_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [3]:
# Generate a categorical variable list
attrit_cat = hr_df.dtypes[hr_df.dtypes=='object'].index.tolist()

In [5]:
# Check the number of unique values in each column
hr_df[attrit_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform using the categorical variable list
enc_df = pd.DataFrame(enc.fit_transform(hr_df[attrit_cat]))

# Add the encoded variables to the DataFrame
enc_df.columns = enc.get_feature_names(attrit_cat)
enc_df

C:\Users\AZ\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1466,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1467,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1468,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1469,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# Merge the encoded features and drop the originals
hr_df = hr_df.merge(enc_df,left_index=True, right_index=True)

hr_df = hr_df.drop(attrit_cat,1)
hr_df

C:\Temp\ipykernel_2792\825695415.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  hr_df = hr_df.drop(attrit_cat,1)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1466,39,613,6,1,1,2062,4,42,2,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1467,27,155,4,3,1,2064,2,87,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1468,49,1023,2,3,1,2065,4,63,2,2,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1469,34,628,8,3,1,2068,2,82,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [8]:
# split the processed data into our features and target arrays
y = hr_df['Attrition_Yes'].values

x = hr_df.drop(['Attrition_Yes','Attrition_No'],1).values

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=78)

C:\Temp\ipykernel_2792\4254985673.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = hr_df.drop(['Attrition_Yes','Attrition_No'],1).values

In [9]:
# Instantiate StandardScaler
scaler = StandardScaler()

# Fit the scaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

In [10]:
# Define the model - deep neural net
n_input_features = len(x_train[0])
hidden_nodes_l1 = 8
hidden_nodes_l2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_l1, input_dim=n_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_l2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the model structure
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [11]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [12]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
35/35 [==============================] - 1s 1ms/step - loss: 0.6334 - accuracy: 0.6434
Epoch 2/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5250 - accuracy: 0.7495
Epoch 3/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4616 - accuracy: 0.8040
Epoch 4/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4230 - accuracy: 0.8249
Epoch 5/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3983 - accuracy: 0.8403
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3807 - accuracy: 0.8485
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3679 - accuracy: 0.8475
Epoch 8/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3571 - accuracy: 0.8512
Epoch 9/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3483 - accuracy: 0.8612
Epoch 10/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3402 - accuracy: 0.8657
Epoch 11/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8666
Epoch 12/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8721
Epoch 13/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3207 - accuracy: 0.8711
Epoch 14/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3146 - accuracy: 0.8757
Epoch 15/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3093 - accuracy: 0.8775
Epoch 16/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3046 - accuracy: 0.8829
Epoch 17/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8829
Epoch 18/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2950 - accuracy: 0.8866
Epoch 19/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2905 - accuracy: 0.8866
Epoch 20/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2862 - accuracy: 0.8875
Epoch 21/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2826 - accuracy: 0.8875
Epoch 22/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2788 - accuracy: 0.8911
Epoch 23/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2755 - accuracy: 0.8929
Epoch 24/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2724 - accuracy: 0.8947
Epoch 25/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2686 - accuracy: 0.8956
Epoch 26/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2666 - accuracy: 0.8947
Epoch 27/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2639 - accuracy: 0.8956
Epoch 28/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2616 - accuracy: 0.8975
Epoch 29/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2580 - accuracy: 0.8975
Epoch 30/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2555 - accuracy: 0.8975
Epoch 31/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2537 - accuracy: 0.8984
Epoch 32/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2505 - accuracy: 0.8993
Epoch 33/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2481 - accuracy: 0.9011
Epoch 34/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2455 - accuracy: 0.9029
Epoch 35/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2439 - accuracy: 0.9002
Epoch 36/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2414 - accuracy: 0.9020
Epoch 37/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2393 - accuracy: 0.8993
Epoch 38/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2375 - accuracy: 0.9020
Epoch 39/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2354 - accuracy: 0.9056
Epoch 40/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2335 - accuracy: 0.9083
Epoch 41/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2321 - accuracy: 0.9065
Epoch 42/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2301 - accuracy: 0.9047
Epoch 43/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2289 - accuracy: 0.9074
Epoch 44/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2269 - accuracy: 0.9083
Epoch 45/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2271 - accuracy: 0.9020
Epoch 46/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2241 - accuracy: 0.9093
Epoch 47/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2223 - accuracy: 0.9093
Epoch 48/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2216 - accuracy: 0.9083
Epoch 49/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2197 - accuracy: 0.9102
Epoch 50/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2181 - accuracy: 0.9074
Epoch 51/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2167 - accuracy: 0.9120
Epoch 52/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2153 - accuracy: 0.9093
Epoch 53/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2154 - accuracy: 0.9102
Epoch 54/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2129 - accuracy: 0.9129
Epoch 55/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2104 - accuracy: 0.9111
Epoch 56/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2099 - accuracy: 0.9120
Epoch 57/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2079 - accuracy: 0.9120
Epoch 58/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2070 - accuracy: 0.9129
Epoch 59/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2055 - accuracy: 0.9156
Epoch 60/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2040 - accuracy: 0.9147
Epoch 61/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2039 - accuracy: 0.9174
Epoch 62/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2018 - accuracy: 0.9156
Epoch 63/100
35/35 [==============================] - 0s 1ms/step - loss: 0.2010 - accuracy: 0.9156
Epoch 64/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1994 - accuracy: 0.9183
Epoch 65/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1988 - accuracy: 0.9183
Epoch 66/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1971 - accuracy: 0.9183
Epoch 67/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1963 - accuracy: 0.9183
Epoch 68/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1956 - accuracy: 0.9201
Epoch 69/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1944 - accuracy: 0.9238
Epoch 70/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1925 - accuracy: 0.9192
Epoch 71/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1909 - accuracy: 0.9201
Epoch 72/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1906 - accuracy: 0.9201
Epoch 73/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1892 - accuracy: 0.9211
Epoch 74/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1879 - accuracy: 0.9229
Epoch 75/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1864 - accuracy: 0.9229
Epoch 76/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1865 - accuracy: 0.9238
Epoch 77/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1851 - accuracy: 0.9220
Epoch 78/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1845 - accuracy: 0.9220
Epoch 79/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1830 - accuracy: 0.9229
Epoch 80/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1824 - accuracy: 0.9238
Epoch 81/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1811 - accuracy: 0.9229
Epoch 82/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1803 - accuracy: 0.9238
Epoch 83/100

35/35 [==============================] - 0s 1ms/step - loss: 0.1800 - accuracy: 0.9220
Epoch 84/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1785 - accuracy: 0.9256
Epoch 85/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1770 - accuracy: 0.9283
Epoch 86/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1768 - accuracy: 0.9238
Epoch 87/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1749 - accuracy: 0.9274
Epoch 88/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1745 - accuracy: 0.9265
Epoch 89/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1730 - accuracy: 0.9274
Epoch 90/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1736 - accuracy: 0.9283
Epoch 91/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1722 - accuracy: 0.9256
Epoch 92/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1714 - accuracy: 0.9301
Epoch 93/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1694 - accuracy: 0.9283
Epoch 94/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1690 - accuracy: 0.9283
Epoch 95/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1678 - accuracy: 0.9310
Epoch 96/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1665 - accuracy: 0.9265
Epoch 97/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1661 - accuracy: 0.9274
Epoch 98/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1649 - accuracy: 0.9310
Epoch 99/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1645 - accuracy: 0.9283
Epoch 100/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1626 - accuracy: 0.9283

In [13]:
# Evaluate the model with the test data

model_loss, model_accuracy = nn.evaluate(x_test_scaled, y_test, verbose=2)

print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.4063 - accuracy: 0.8832 - 156ms/epoch - 13ms/step
Loss: 0.4062631130218506, Accuracy: 0.883152186870575